### ISSUE TITLE
alertify

### ISSUE THREAD

**Issue by omarb13** [alertifyjs/alertify.js#51] opened 2015-10-12 20:28 UTC
alertify.log("Will stay until clicked", "", 0);

is still closing automatically..

**Comment by bradberger** [comment] 2015-10-12 21:04
Can you provide a jsfiddle/jsbin example of it not working? From what I can tell based on the examples on the website, it's working fine there, so an example to reproduce the issue would be helpful. 

Might be worth noting in version 1 and up that it will close if there are multiple log messages and it gets "pushed" into hiding, that's part of the design.

**Comment by omarb13** [comment] 2015-10-12 22:16
http://jsfiddle.net/mpqqhrc6/

**Comment by bradberger** [comment] 2015-10-13 06:20
Thanks. Turns out that the website documentation is outdated, the code example needs to be updated. It should be:

```javascript
alertify.delay(0).log("Will stay until clicked")
```

**Comment by bradberger** [comment] 2015-10-13 07:06
Changes are being pushed to the website now, so closing this. Thanks!

**Closed by bradberger** 2015-10-13 07:06 UTC
Labels: bug

**Comment by omarb13** [comment] 2015-10-13 09:27
thx.. but after doing the changes based on that.. the alerts can't be dismissed even when they are clicked... 
http://jsfiddle.net/mpqqhrc6/1/

**Comment by bradberger** [comment] 2015-10-13 10:04
Yeah, close on click isn't the default in this version, so:

```javascript
alertify.closeLogOnClick(true).delay(0).log("Will stay until clicked");
```

It can be set once, too, if that's the default functionality you're looking for, as in your example:

```javascript
alertify.closeLogOnClick(true);

$('button').click(function() {
	alertify.delay(0).log("Will stay until clicked");
});
```
