### ISSUE TITLE
Click on log message won't close it in 1.0.5

### ISSUE THREAD

**Issue by pzgz** [alertifyjs/alertify.js#60] opened 2015-12-04 18:48 UTC
Please refer to following fiddle.

http://jsfiddle.net/mpqqhrc6/2/

Changed to 1.0.4 can fix the issue.

**Comment by bradberger** [comment] 2015-12-04 19:04
This is actually a duplicate of #56 and it's been fixed in 1.0.6, it's just that the related git tag was missing, so I've added it now, and you should be good to go with that version.

**Closed by bradberger** 2015-12-04 19:04 UTC
